# Generated by Django 3.2.3 on 2021-05-27 09:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210527_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
